In [1]:
import torch

In [2]:
a = torch.randn(3, 4)
a

tensor([[-0.7821,  1.0752,  0.4269, -0.1468],
        [ 0.4429, -0.6634, -0.3814,  0.0851],
        [-0.6316,  0.0389,  0.8515,  1.0144]])

In [3]:
a = a.reshape(12, 1)
a

tensor([[-0.7821],
        [ 1.0752],
        [ 0.4269],
        [-0.1468],
        [ 0.4429],
        [-0.6634],
        [-0.3814],
        [ 0.0851],
        [-0.6316],
        [ 0.0389],
        [ 0.8515],
        [ 1.0144]])

In [4]:
a = a.reshape(1, 12)
a

tensor([[-0.7821,  1.0752,  0.4269, -0.1468,  0.4429, -0.6634, -0.3814,  0.0851,
         -0.6316,  0.0389,  0.8515,  1.0144]])

In [8]:
a = a.reshape(3, 4)
a

tensor([[-0.7821,  1.0752,  0.4269, -0.1468],
        [ 0.4429, -0.6634, -0.3814,  0.0851],
        [-0.6316,  0.0389,  0.8515,  1.0144]])

In [9]:
a = a.view(3, 1, 4)
a

tensor([[[-0.7821,  1.0752,  0.4269, -0.1468]],

        [[ 0.4429, -0.6634, -0.3814,  0.0851]],

        [[-0.6316,  0.0389,  0.8515,  1.0144]]])

In [11]:
a = a.expand(-1, 2, -1)
a

tensor([[[-0.7821,  1.0752,  0.4269, -0.1468],
         [-0.7821,  1.0752,  0.4269, -0.1468]],

        [[ 0.4429, -0.6634, -0.3814,  0.0851],
         [ 0.4429, -0.6634, -0.3814,  0.0851]],

        [[-0.6316,  0.0389,  0.8515,  1.0144],
         [-0.6316,  0.0389,  0.8515,  1.0144]]])